spring.datasource.url=${B_DB_URL}
spring.datasource.username=${B_DB_USER}
spring.datasource.password=${B_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=never
