CREATE TABLE IF NOT EXISTS demo_user (
 sso_subject VARCHAR(128) PRIMARY KEY,
 username VARCHAR(128) NOT NULL,
 role VARCHAR(32) NOT NULL DEFAULT 'DEMO_USER',
 enabled BOOLEAN NOT NULL DEFAULT TRUE
);
